import type { TypographyRole, TypographySettings } from '../theme-settings';

/* Font registry: the single source of allowed values for the ui.typography setting
   (a controlled enum, not a free-form font-family string).
   Adding a custom font = add one entry to THEME_FONT_REGISTRY (the ThemeFontId type
   is derived automatically from entry ids):
   - subset-pipeline fonts must supply their own woff2 and @font-face (see the
     README's "Fonts & licensing" section);
   - astro-fonts-api fonts only need provider + familyName; they're downloaded and
     self-hosted automatically at build time.
   acquisition semantics:
   - subset-pipeline: self-hosted font, woff2 generated by npm run font:build
     (content-aware subsetting via pyftsubset), @font-face declared in global.css;
   - system: a pure system font stack, zero downloads;
   - astro-fonts-api: downloaded and self-hosted by the Astro Fonts API at build
     time — zero third-party requests on the page. */

export type ThemeFontLocalVariant = {
  src: string;
  weight: number | string;
  style: 'normal' | 'italic';
};

type ThemeFontRegistryEntryBase = {
  id: string;
  label: string;
  /* Short name and source note used by the admin console's font cards: cardLabel +
     badge are shown on the card (badge is small light-gray text); label/sizeHint
     are registry metadata (full name and acquisition-cost note) that the current
     admin UI doesn't render directly. */
  cardLabel: string;
  badge: string;
  roles: readonly TypographyRole[];
  /* fallbacks are stored verbatim as CSS literals (quotes included), so the
     default role resolution matches global.css tokens character-for-character. */
  fallbacks: readonly string[];
  license: string | null;
  sizeHint: string;
};

/* A union type discriminated by acquisition/provider: an illegal combination (e.g.
   astro-fonts-api + provider:null, or local with no localVariants) fails to compile
   right at `as const satisfies` instead of silently reaching the dropdown. */
export type ThemeFontRegistryEntry =
  | (ThemeFontRegistryEntryBase & {
      acquisition: 'system';
      provider: null;
      familyName: null;
      weights: readonly [];
    })
  | (ThemeFontRegistryEntryBase & {
      acquisition: 'subset-pipeline';
      provider: null;
      familyName: string;
      weights: readonly number[];
    })
  | (ThemeFontRegistryEntryBase & {
      acquisition: 'astro-fonts-api';
      provider: 'google' | 'fontsource';
      familyName: string;
      weights: readonly number[];
      /* The subset downloaded from the remote provider, defaults to ['latin'];
         CJK entries must declare it explicitly (e.g. ['chinese-simplified', 'latin']),
         otherwise Chinese glyphs are excluded from the build and silently fall
         back. */
      subsets?: readonly string[];
    })
  | (ThemeFontRegistryEntryBase & {
      acquisition: 'astro-fonts-api';
      provider: 'local';
      familyName: string;
      weights: readonly number[];
      /* Font file path (relative to project root, e.g. './src/assets/fonts/xxx.woff2').
         Zero network dependency at build time — still generates @font-face and a
         metric-aligned fallback via the Astro Fonts API. The preferred choice for
         builds on restricted networks or offline. */
      localVariants: readonly ThemeFontLocalVariant[];
    });

export type ThemeFontAcquisition = ThemeFontRegistryEntry['acquisition'];
export type ThemeFontProvider = ThemeFontRegistryEntry['provider'];

export const THEME_FONT_REGISTRY = [
  {
    id: 'noto-serif-sc',
    label: 'Noto Serif SC',
    cardLabel: 'Noto Serif SC',
    badge: 'Self-hosted subset',
    roles: ['readable', 'brand'],
    acquisition: 'subset-pipeline',
    provider: null,
    familyName: 'Noto Serif SC',
    fallbacks: ['ui-serif', 'Georgia', '"Times New Roman"', '"Songti SC"', 'serif'],
    weights: [400, 600],
    license: 'OFL-1.1',
    sizeHint: 'Self-hosted content subset'
  },
  {
    id: 'lxgw-wenkai-lite',
    label: 'LXGW WenKai Lite',
    cardLabel: 'LXGW WenKai Lite',
    badge: 'Self-hosted subset',
    roles: ['readable', 'copy', 'brand'],
    acquisition: 'subset-pipeline',
    provider: null,
    familyName: 'LXGW WenKai Lite',
    fallbacks: ['"Kaiti SC"', '"STKaiti"', 'serif'],
    weights: [400],
    license: 'OFL-1.1',
    sizeHint: 'Self-hosted content subset'
  },
  {
    id: 'system-serif',
    label: 'System serif (Songti / Georgia)',
    cardLabel: 'System serif',
    badge: 'Zero download',
    roles: ['readable'],
    acquisition: 'system',
    provider: null,
    familyName: null,
    fallbacks: ['ui-serif', 'Georgia', '"Times New Roman"', '"Songti SC"', 'serif'],
    weights: [],
    license: null,
    sizeHint: 'Zero download'
  },
  {
    id: 'serif-georgia',
    label: 'System serif (Georgia)',
    cardLabel: 'Georgia',
    badge: 'Zero download',
    roles: ['brand'],
    acquisition: 'system',
    provider: null,
    familyName: null,
    fallbacks: ['Georgia', 'serif'],
    weights: [],
    license: null,
    sizeHint: 'Zero download'
  },
  {
    id: 'system-kai',
    label: 'System Kaiti (Kaiti / STKaiti)',
    cardLabel: 'System Kaiti',
    badge: 'Zero download',
    roles: ['copy'],
    acquisition: 'system',
    provider: null,
    familyName: null,
    fallbacks: ['"Kaiti SC"', '"STKaiti"', 'serif'],
    weights: [],
    license: null,
    sizeHint: 'Zero download'
  },
  {
    id: 'system-mono',
    label: 'System monospace (Sarasa / SF Mono)',
    cardLabel: 'System monospace',
    badge: 'Zero download',
    roles: ['mono'],
    acquisition: 'system',
    provider: null,
    familyName: null,
    fallbacks: [
      '"Sarasa Mono SC"',
      '"Noto Sans Mono CJK SC"',
      'ui-monospace',
      'SFMono-Regular',
      'Menlo',
      'Monaco',
      'Consolas',
      '"Liberation Mono"',
      '"Courier New"',
      'monospace'
    ],
    weights: [],
    license: null,
    sizeHint: 'Zero download'
  },
  {
    id: 'jetbrains-mono',
    label: 'JetBrains Mono (Latin monospace)',
    cardLabel: 'JetBrains Mono',
    badge: 'Downloaded at build time',
    roles: ['mono'],
    acquisition: 'astro-fonts-api',
    // fontsource is distributed via jsDelivr/R2, which is more reachable than
    // fonts.google.com in regions where the latter is blocked.
    provider: 'fontsource',
    familyName: 'JetBrains Mono',
    fallbacks: [
      '"Sarasa Mono SC"',
      '"Noto Sans Mono CJK SC"',
      'ui-monospace',
      'SFMono-Regular',
      'Menlo',
      'Monaco',
      'Consolas',
      '"Liberation Mono"',
      '"Courier New"',
      'monospace'
    ],
    weights: [400],
    license: 'OFL-1.1',
    sizeHint: 'Downloaded and self-hosted at build time (latin; CJK falls back to system monospace)'
  },
  {
    id: 'ibm-plex-sans',
    label: 'IBM Plex Sans',
    cardLabel: 'IBM Plex Sans',
    badge: 'Downloaded at build time',
    roles: ['readable', 'copy'],
    acquisition: 'astro-fonts-api',
    provider: 'fontsource',
    familyName: 'IBM Plex Sans',
    fallbacks: ['ui-sans-serif', '-apple-system', '"Segoe UI"', 'Roboto', 'sans-serif'],
    weights: [400, 600],
    license: 'OFL-1.1',
    sizeHint: 'Downloaded and self-hosted at build time (latin subset)'
  },
  {
    id: 'fira-code',
    label: 'Fira Code (Latin monospace, ligatures)',
    cardLabel: 'Fira Code',
    badge: 'Downloaded at build time',
    roles: ['mono'],
    acquisition: 'astro-fonts-api',
    provider: 'fontsource',
    familyName: 'Fira Code',
    fallbacks: [
      '"Sarasa Mono SC"',
      '"Noto Sans Mono CJK SC"',
      'ui-monospace',
      'SFMono-Regular',
      'Menlo',
      'Monaco',
      'Consolas',
      '"Liberation Mono"',
      '"Courier New"',
      'monospace'
    ],
    weights: [400],
    license: 'OFL-1.1',
    sizeHint: 'Downloaded and self-hosted at build time (latin; CJK falls back to system monospace)'
  }
] as const satisfies readonly ThemeFontRegistryEntry[];

export type ThemeFontId = (typeof THEME_FONT_REGISTRY)[number]['id'];

/* The single source of the four-role enum: adding a role only requires changing
   this and the TypographyRole type; every consumer always iterates this constant. */
export const TYPOGRAPHY_ROLES = ['readable', 'copy', 'mono', 'brand'] as const satisfies readonly TypographyRole[];

export const THEME_TYPOGRAPHY_DEFAULT: TypographySettings = {
  readable: 'ibm-plex-sans',
  copy: 'ibm-plex-sans',
  mono: 'system-mono',
  brand: 'serif-georgia'
};

export type ThemeFontOption = {
  id: ThemeFontId;
  cardLabel: string;
  badge: string;
  /* The font-family stack used for card previews (see getThemeFontPreviewStack),
     fed directly into CSS font-family. */
  previewStack: string;
};

const entryHasRole = (entry: ThemeFontRegistryEntry, role: TypographyRole): boolean =>
  entry.roles.includes(role);

const buildRoleFontIdSet = (role: TypographyRole): ReadonlySet<string> =>
  new Set(THEME_FONT_REGISTRY.filter((entry) => entryHasRole(entry, role)).map((entry) => entry.id));

const ROLE_FONT_ID_SETS = Object.fromEntries(
  TYPOGRAPHY_ROLES.map((role) => [role, buildRoleFontIdSet(role)])
) as Record<TypographyRole, ReadonlySet<string>>;

export const isThemeFontIdForRole = (role: TypographyRole, value: string): value is ThemeFontId =>
  ROLE_FONT_ID_SETS[role].has(value);

/* The single validate+fallback implementation (validates after trimming, returns
   undefined if invalid): shared by canonicalize / theme-settings / config-time raw
   parsing, so the same semantics aren't maintained separately in three places. */
export const asThemeFontIdForRole = (role: TypographyRole, value: unknown): ThemeFontId | undefined => {
  const trimmed = typeof value === 'string' ? value.trim() : '';
  return isThemeFontIdForRole(role, trimmed) ? trimmed : undefined;
};

export const getThemeFontOptionsForRole = (role: TypographyRole): ThemeFontOption[] =>
  THEME_FONT_REGISTRY
    .filter((entry) => entryHasRole(entry, role))
    .map(({ id, cardLabel, badge }) => ({
      id,
      cardLabel,
      badge,
      previewStack: getThemeFontPreviewStack(id)
    }));

export const getThemeFontRegistryEntry = (id: ThemeFontId): ThemeFontRegistryEntry | undefined =>
  THEME_FONT_REGISTRY.find((entry) => entry.id === id);

/* The admin console's card-preview-only stack: no var(--font-*). An unselected
   astro-fonts-api font has no corresponding variable on the page, and an
   undefined var() invalidates the entire font-family declaration (dropping even
   the literal fallback along with it) — so previews always render with a literal
   family name + fallback on a best-effort basis, without downloading extra fonts
   just for the preview. */
export const getThemeFontPreviewStack = (id: ThemeFontId): string => {
  const entry = getThemeFontRegistryEntry(id);
  if (!entry) return '';
  const families = entry.familyName ? [`"${entry.familyName}"`, ...entry.fallbacks] : [...entry.fallbacks];
  return families.join(', ');
};

export const getThemeFontStack = (id: ThemeFontId): string => {
  const entry = getThemeFontRegistryEntry(id);
  if (!entry) return '';
  if (entry.acquisition === 'astro-fonts-api') {
    // The Astro Fonts API's cssVariable already includes the font family and a
    // metric-aligned fallback; append the registry fallback to catch CJK glyphs.
    return [`var(--font-${entry.id})`, ...entry.fallbacks].join(', ');
  }
  return getThemeFontPreviewStack(id);
};

/* The entries in the current typography selection that need Astro Fonts API
   downloads at build time; astro.config and BaseLayout share this same check. */
export const getSelectedAstroApiFonts = (typography: TypographySettings): ThemeFontRegistryEntry[] => {
  const selected = new Set<string>(TYPOGRAPHY_ROLES.map((role) => typography[role]));
  return THEME_FONT_REGISTRY.filter(
    (entry) => entry.acquisition === 'astro-fonts-api' && selected.has(entry.id)
  );
};

/* For astro.config to consume a hand-read ui.json directly at config time (without
   going through the full theme-settings pipeline): any invalid/missing value
   falls back to the default, matching canonicalize's tolerant semantics. */
export const resolveTypographyFromRawUiSettings = (raw: unknown): TypographySettings => {
  const isRecord = (value: unknown): value is Record<string, unknown> =>
    typeof value === 'object' && value !== null && !Array.isArray(value);
  const typography = isRecord(raw) && isRecord(raw.typography) ? raw.typography : {};
  const pick = (role: TypographyRole): ThemeFontId =>
    asThemeFontIdForRole(role, typography[role]) ?? THEME_TYPOGRAPHY_DEFAULT[role];
  return { readable: pick('readable'), copy: pick('copy'), mono: pick('mono'), brand: pick('brand') };
};

/* Generates a --font-* override only for roles that deviate from the default;
   the default state outputs null, keeping global.css's :root tokens as the sole
   default source. */
export const getTypographyStyleOverride = (typography: TypographySettings): string | null => {
  const declarations = TYPOGRAPHY_ROLES
    .filter((role) => typography[role] !== THEME_TYPOGRAPHY_DEFAULT[role])
    .map((role) => `--font-${role}: ${getThemeFontStack(typography[role])}`);
  return declarations.length ? declarations.join('; ') : null;
};
